### ISSUE TITLE
Illegal memory access was encounterd

### ISSUE THREAD

**Issue by coderasm** [alexis78/ccminer#5]
This occurs usually within the first 5 minutes of running.

![ccminer_crash](https://user-images.githubusercontent.com/446396/28391510-2d65926a-6c93-11e7-9423-366b4040882f.PNG)

The command and miner type I am using.

![sib_miner](https://user-images.githubusercontent.com/446396/28391687-d28d5138-6c93-11e7-962f-da614cde1a11.PNG)

**Comment by alexis78** [comment]
Is this issue happening when you use -i 22 or -i 21 too?

**Comment by coderasm** [comment]
Downgraded to 382.53 on windows 10 home. That appears to have worked. Thank you.
